[2023-10-31T22:34:58.708+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: la_test.load_channels manual__2023-10-31T16:19:52.345619+00:00 [queued]>
[2023-10-31T22:34:58.712+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: la_test.load_channels manual__2023-10-31T16:19:52.345619+00:00 [queued]>
[2023-10-31T22:34:58.712+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-31T22:34:58.716+0100] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_channels> on 2023-10-31 16:19:52.345619+00:00
[2023-10-31T22:34:58.719+0100] {standard_task_runner.py:57} INFO - Started process 65599 to run task
[2023-10-31T22:34:58.721+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'la_test', 'load_channels', 'manual__2023-10-31T16:19:52.345619+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/test_aj.py', '--cfg-path', '/var/folders/4w/73_t653s0rz1z847_g217g2h0000gn/T/tmp_a_cd3ta']
[2023-10-31T22:34:58.722+0100] {standard_task_runner.py:85} INFO - Job 39: Subtask load_channels
[2023-10-31T22:34:58.741+0100] {task_command.py:416} INFO - Running <TaskInstance: la_test.load_channels manual__2023-10-31T16:19:52.345619+00:00 [running]> on host mbp21-14
[2023-10-31T22:34:58.761+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='la_test' AIRFLOW_CTX_TASK_ID='load_channels' AIRFLOW_CTX_EXECUTION_DATE='2023-10-31T16:19:52.345619+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-31T16:19:52.345619+00:00'
[2023-10-31T22:34:58.763+0100] {base.py:73} INFO - Using connection ID 'la_db_teams_aj' for task execution.
[2023-10-31T22:34:58.795+0100] {base.py:73} INFO - Using connection ID 'la_db_teams_aj' for task execution.
[2023-10-31T22:34:58.834+0100] {logging_mixin.py:151} WARNING - /Users/nick/airflow/dags/operators/load_operators.py:19 SAWarning: Skipped unsupported reflection of expression-based index idx_ab_register_user_username
[2023-10-31T22:34:58.866+0100] {logging_mixin.py:151} WARNING - /Users/nick/airflow/dags/operators/load_operators.py:19 SAWarning: Skipped unsupported reflection of expression-based index idx_ab_user_username
[2023-10-31T22:34:59.462+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/nick/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/Users/nick/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nick/airflow/dags/operators/load_operators.py", line 21, in load_df_to_db
    df = read_csv(dataframe_fp, index_col=0)
  File "/Users/nick/miniforge3/envs/airflow_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/nick/miniforge3/envs/airflow_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/nick/miniforge3/envs/airflow_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/nick/miniforge3/envs/airflow_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/Users/nick/miniforge3/envs/airflow_env/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nick/airflow/data/csv/teams_channels.csv'
[2023-10-31T22:34:59.470+0100] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=la_test, task_id=load_channels, execution_date=20231031T161952, start_date=20231031T213458, end_date=20231031T213459
[2023-10-31T22:34:59.512+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 39 for task load_channels ([Errno 2] No such file or directory: '/Users/nick/airflow/data/csv/teams_channels.csv'; 65599)
[2023-10-31T22:34:59.518+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-31T22:34:59.527+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
